### PR TITLE
Fix Element Type Error and Refactor Test Mocks for RemoteControlScreen tests

### LINKED ISSUE #36: Fix Component Detection Error in remotecontrol/index.test.tsx with React Native Testing Library Compatibility
When running tests, the following error occurs:

> `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. There seems to be an issue with your configuration that prevents React Native Testing Library from working correctly.
Please check if you are using compatible versions of React Native and React Native Testing Library.`

This error may indicate an export issue or a compatibility problem between **React Native** and **React Native Testing Library**.

#### Task:
- Review component imports/exports to ensure they’re correctly structured.
- Verify that the versions of **React Native** and **React Native Testing Library** are compatible, and update them if needed.
- Implement fixes to prevent this error from recurring.

> **Note:** This branch `[fix/rmctl-test]` was created from `[test/tmctl]` to address this issue in tests and ensure compatibility.

### PR DESCRIPTION
**Pull request by TuanDangNguyen2003**
### **Problem:**
- Encountered the error: "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined." 
- The issue stemmed from incorrect or missing imports for components, which caused the React Native Testing Library to fail.

### **How I Fixed It:**
1. Initially, I used ChatGPT for quick suggestions, but all of them had already been addressed by the existing tests.
2. After about 2 hours of troubleshooting, I discovered the issue might be caused by the `RemoteControlScreen` being undefined, despite being correctly imported.
3. I examined the `RemoteControlScreen` component in `(app)/lectures/remotecontrol/index.tsx`. It rendered correctly on the phone but not in the test environment.
4. I simplified the component by commenting out the code, leaving only a basic display, and reran the test—still no success.
5. I then created a new, minimal test, mocking each dependency one by one. Eventually, I identified that an old, unused mock (`jest.mock('react-native', () => ({ Vibration: { vibrate: jest.fn() } }));`) was breaking the test. Considering the functionality of RemoteControlScreen, it is not necessary to have a mock for vibration. Thus I safely deleted it.
6. After removing this mock, the screen rendered correctly in the test. 
7. Finally, I mocked the necessary data and components that the `RemoteControlScreen` depends on to finalize the test.

### **Changes:**
- **Fixed the undefined component issue** by removing the problematic mock.
- **Refactored the test** by cleaning up duplicated mocks and simplifying the test setup.

### **Testing:**
- The test now runs successfully without errors, and the screen renders as expected.

- Verified that all mocks are correctly set up, and the screen behaves as expected in the test.
**Coverage**

| File Name   |Line Coverage (%) | 
|----------------|:-----------------:|
| `(app)/lectures/remotecontrol/index.tsx` | 85.29 %               |

Fixed #36

### CODE REVIEW

File: edweiss-app/app/(app)/lectures/remotecontrol/index.tsx [hunk 1]
```diff
@@ -33,7 +33,7 @@ const RemoteControlScreen: ApplicationRoute = () => {
     const { courseNameString, lectureIdString } = useLocalSearchParams();
     const courseName = courseNameString as string;
     const lectureId = lectureIdString as string;
-    const [lectureDoc] = usePrefetchedDynamicDoc(CollectionOf<Lecture>(`courses/${courseName}/lectures`), lectureId, undefined);
+    const [lectureDoc] = usePrefetchedDynamicDoc(CollectionOf<Lecture>(`courses/${courseName}/lectures`), lectureId, undefined) || [];
```
Comment (adamm-alaoui-pro) [inline edweiss-app/app/(app)/lectures/remotecontrol/index.tsx:36]: I think that I understand more clearly why did it failed, it was because the `lectureDoc` was undefined. It great that you fixed it using the `fail safe default` principle. Good job 👍.

File: edweiss-app/app/(app)/lectures/remotecontrol/index.tsx [hunk 2]
```diff
@@ -53,12 +53,14 @@ const RemoteControlScreen: ApplicationRoute = () => {
...
 
     return (
-        <AbstractRmtCrl
-            handleRight={() => handleRight(isRecording, currentPage, totalPages, setIsRecording, setCurrentPage, stopRecording)}
-            handleLeft={() => handleLeft(isRecording, currentPage, setIsRecording, setCurrentPage, stopRecording)}
-            handleMic={() => handleMic(isRecording, setIsRecording, startRecording, stopRecording)}
-            isRecording={isRecording}
-        />
+        <>
+            {<AbstractRmtCrl
```
Comment (adamm-alaoui-pro) [inline edweiss-app/app/(app)/lectures/remotecontrol/index.tsx:57]: A small reformat might be needed, but yeah surrounding the component within `<></>` may have done the trick. When I look back to it I realize that I may have to put them in the `todo/create` and `todo/edit` screens maybe 😁.

File: edweiss-app/__test__/app/(app)/lectures/remotecontrol/index.test.tsx [hunk 3]
```diff
@@ -103,16 +89,11 @@ jest.mock('@react-native-firebase/messaging', () => ({
     })),
 }));
 
-
-
-
 // Mock react-native-pdf to prevent native calls
```
Comment (adamm-alaoui-pro) [inline edweiss-app/__test__/app/(app)/lectures/remotecontrol/index.test.tsx:92]: We might need to remove this, as we are not displaying any `pdf` within the remote control 😉.

File: edweiss-app/__test__/app/(app)/lectures/remotecontrol/index.test.tsx [hunk 4]
```diff
@@ -23,7 +26,13 @@ jest.mock('@/config/i18config', () => ({
...
 
 jest.mock('expo-router', () => ({
-    useLocalSearchParams: jest.fn(),
+    router: { push: jest.fn() },
+    Stack: {
+        Screen: jest.fn(({ options }) => (
+            <>{options.title}</> // Simulate rendering the title for the test
+        )),
+    },
+    useLocalSearchParams: jest.fn(() => ({ courseNameString: 'testCourse', lectureIdString: 'testLectureId' }))
```
Comment (adamm-alaoui-pro) [inline edweiss-app/__test__/app/(app)/lectures/remotecontrol/index.test.tsx:35]: Good catch 😋, yes I agree with your mock. It makes more sens to directly put the `useLocalSearchParam` within the `expo-router` mock.

**Review by adamm-alaoui-pro — APPROVED** [review]
Before all, I would like to thank you for your devotion to helping me solve this issue. As I was preparing the maestro-CI integration, it removed me weight on my shoulders 🦾.

I have started to modularize the code applying more the `MVVM` design pattern, but I still got issues with the `render` function. You came at the right moment and provided a good external point of view.

I have made some view remarks, were I point-out some of your changes.

I have re-ran the test on my laptop, to check if the fix was by luck only are windows and CI compliant 🙃. They works fine on linux. You have my approval to merge back in my branch `test/rmtctl` 🚀.

File: edweiss-app/__test__/app/(app)/lectures/remotecontrol/index.test.tsx (hunk 3 above)
Comment (TuanDangNguyen2003) [reply edweiss-app/__test__/app/(app)/lectures/remotecontrol/index.test.tsx:92]: Yup it is true. I will remove this and re-test to see if everything works. I agree that we should always have a clean, short code at the end :D

File: edweiss-app/app/(app)/lectures/remotecontrol/index.tsx (hunk 1 above)
Comment (TuanDangNguyen2003) [reply edweiss-app/app/(app)/lectures/remotecontrol/index.tsx:36]: Yup, it was one of the factor for the render to not render everything. It was just a safe feature that I implemented because you already have one protector, which is the checking if lecture is undefined or not just below the code. Nevertheless, having one more safety feature helps our code to be more sure, less prone of errors.

File: edweiss-app/__test__/app/(app)/lectures/remotecontrol/index.test.tsx (hunk 3 above)
Comment (adamm-alaoui-pro) [reply edweiss-app/__test__/app/(app)/lectures/remotecontrol/index.test.tsx:92]: Great 😁!

File: edweiss-app/app/(app)/lectures/remotecontrol/index.tsx (hunk 1 above)
Comment (adamm-alaoui-pro) [reply edweiss-app/app/(app)/lectures/remotecontrol/index.tsx:36]: I could not have stated it in a more concise fashion that you did 🤐.

**Comment by TuanDangNguyen2003** [comment]
I just deleted the pdf mock and it was not necessary for the test to keep it concise, short and simple. There is no problem. While we are working on the end2end, I figure that it would be more efficient if I help you on your test while, with the linux laptop you have, you set up the maestro. Of course I am right next to you for any major problem about ndk, sdk version etc during the setup of end2end, other than that, I am happy to help resolving the problem you have with your test.
